-- Roda Festa RF-ADMIN-COMMERCIAL-V1
-- Persistent catalog overrides + append-only admin quote revisions.

begin;

create table if not exists public.product_catalog_overrides (
  product_id text primary key,
  product_data jsonb not null,
  active boolean not null default true,
  revision integer not null default 1,
  updated_at timestamptz not null default now(),
  updated_by text not null
);

create table if not exists public.product_catalog_history (
  id bigint generated by default as identity primary key,
  product_id text not null,
  revision integer not null,
  product_data jsonb not null,
  active boolean not null,
  changed_at timestamptz not null default now(),
  changed_by text not null,
  action text not null,
  constraint product_catalog_history_action_check
    check (action in ('CREATE', 'UPDATE', 'DEACTIVATE', 'REACTIVATE'))
);

create unique index if not exists product_catalog_history_product_revision_uidx
  on public.product_catalog_history (product_id, revision);
create index if not exists product_catalog_history_changed_at_idx
  on public.product_catalog_history (changed_at desc);

alter table public.planning_sessions
  add column if not exists admin_effective_snapshot jsonb,
  add column if not exists admin_revision_history jsonb not null default '[]'::jsonb,
  add column if not exists admin_commercial_revision integer not null default 0,
  add column if not exists admin_commercial_updated_at timestamptz,
  add column if not exists admin_commercial_updated_by text;

comment on table public.product_catalog_overrides is
  'Current server-managed product catalog overrides. Base code catalog remains fallback/seed.';
comment on table public.product_catalog_history is
  'Append-only audit trail for product catalog changes.';
comment on column public.planning_sessions.admin_effective_snapshot is
  'Latest server-authoritative admin commercial revision. Original final_proposal_snapshot remains immutable.';
comment on column public.planning_sessions.admin_revision_history is
  'Append-only metadata/history of administrative commercial revisions.';

commit;
