-- Roda Festa RF-ADMIN-COMMERCIAL-V1
-- Persistent catalog overrides + append-only admin quote revisions.

begin;

create table if not exists public.product_catalog_overrides (
  product_id text primary key,
  product_data jsonb not null,
  active boolean not null default true,
  revision integer not null default 1,
  updated_at timestamptz not null default now(),
  updated_by text not null
);

create table if not exists public.product_catalog_history (
  id bigint generated by default as identity primary key,
  product_id text not null,
  revision integer not null,
  product_data jsonb not null,
  active boolean not null,
  changed_at timestamptz not null default now(),
  changed_by text not null,
  action text not null,
  constraint product_catalog_history_action_check
    check (action in ('CREATE', 'UPDATE', 'DEACTIVATE', 'REACTIVATE'))
);

create unique index if not exists product_catalog_history_product_revision_uidx
  on public.product_catalog_history (product_id, revision);
create index if not exists product_catalog_history_changed_at_idx
  on public.product_catalog_history (changed_at desc);

alter table public.planning_sessions
  add column if not exists admin_effective_snapshot jsonb,
  add column if not exists admin_revision_history jsonb not null default '[]'::jsonb,
  add column if not exists admin_commercial_revision integer not null default 0,
  add column if not exists admin_commercial_updated_at timestamptz,
  add column if not exists admin_commercial_updated_by text;

-- Brigadeiro no tacho: 80 g por convidado real, R$ 12 por porção.
-- Meio a meio = 40 g chocolate + 40 g Ninho na mesma porção de 80 g.
-- A capacidade por hora ainda não foi medida; permanece NULL para não inventar
-- um parâmetro que depois será usado pelo futuro gate de peak capacity.
insert into public.product_catalog_overrides (
  product_id, product_data, active, revision, updated_at, updated_by
) values
(
  'brigadeiro-tacho-chocolate',
  '{"id":"brigadeiro-tacho-chocolate","name":"Brigadeiro no tacho - Chocolate","description":"Porção de 80 g por pessoa","commercialCategory":"Brigadeiro no tacho","operationalGroup":"tacho","productionPerHour":null,"suggestedUnitsPerEquivalentGuest":1,"lotSize":1,"unitPrice":12,"priceUnit":"portion80g","portionGrams":80,"active":true,"consignment":false,"countsAsMainCart":true,"catalogSchemaVersion":1}'::jsonb,
  true, 1, now(), 'migration:20260831'
),
(
  'brigadeiro-tacho-ninho',
  '{"id":"brigadeiro-tacho-ninho","name":"Brigadeiro no tacho - Leite Ninho","description":"Porção de 80 g por pessoa","commercialCategory":"Brigadeiro no tacho","operationalGroup":"tacho","productionPerHour":null,"suggestedUnitsPerEquivalentGuest":1,"lotSize":1,"unitPrice":12,"priceUnit":"portion80g","portionGrams":80,"active":true,"consignment":false,"countsAsMainCart":true,"catalogSchemaVersion":1}'::jsonb,
  true, 1, now(), 'migration:20260831'
),
(
  'brigadeiro-tacho-meio-a-meio',
  '{"id":"brigadeiro-tacho-meio-a-meio","name":"Brigadeiro no tacho - Meio a meio","description":"40 g chocolate + 40 g Leite Ninho por pessoa","commercialCategory":"Brigadeiro no tacho","operationalGroup":"tacho","productionPerHour":null,"suggestedUnitsPerEquivalentGuest":1,"lotSize":1,"unitPrice":12,"priceUnit":"portion80g","portionGrams":80,"active":true,"consignment":false,"countsAsMainCart":true,"catalogSchemaVersion":1}'::jsonb,
  true, 1, now(), 'migration:20260831'
)
on conflict (product_id) do nothing;

insert into public.product_catalog_history (
  product_id, revision, product_data, active, changed_at, changed_by, action
)
select
  product_id,
  revision,
  product_data,
  active,
  updated_at,
  updated_by,
  'CREATE'
from public.product_catalog_overrides
where product_id in (
  'brigadeiro-tacho-chocolate',
  'brigadeiro-tacho-ninho',
  'brigadeiro-tacho-meio-a-meio'
)
on conflict (product_id, revision) do nothing;

comment on table public.product_catalog_overrides is
  'Current server-managed product catalog overrides. Base code catalog remains fallback/seed.';
comment on table public.product_catalog_history is
  'Append-only audit trail for product catalog changes.';
comment on column public.planning_sessions.admin_effective_snapshot is
  'Latest server-authoritative admin commercial revision. Original final_proposal_snapshot remains immutable.';
comment on column public.planning_sessions.admin_revision_history is
  'Append-only metadata/history of administrative commercial revisions.';

commit;
