-- Roda Festa RF-ADMIN-COMMERCIAL-V1
-- Persistent catalog overrides + append-only admin quote revisions.
-- Server-side only: browser roles receive no direct table/function access.

begin;

create table if not exists public.product_catalog_overrides (
  product_id text primary key,
  product_data jsonb not null,
  active boolean not null default true,
  revision integer not null default 1 check (revision >= 1),
  updated_at timestamptz not null default now(),
  updated_by text not null
);

create table if not exists public.product_catalog_history (
  id bigint generated by default as identity primary key,
  product_id text not null,
  revision integer not null check (revision >= 1),
  product_data jsonb not null,
  active boolean not null,
  changed_at timestamptz not null default now(),
  changed_by text not null,
  action text not null,
  constraint product_catalog_history_action_check
    check (action in ('CREATE', 'UPDATE', 'DEACTIVATE', 'REACTIVATE'))
);

create unique index if not exists product_catalog_history_product_revision_uidx
  on public.product_catalog_history (product_id, revision);
create index if not exists product_catalog_history_changed_at_idx
  on public.product_catalog_history (changed_at desc);

alter table public.product_catalog_overrides enable row level security;
alter table public.product_catalog_history enable row level security;

-- Deliberadamente nenhuma policy para anon/authenticated.
-- O navegador nunca acessa estas tabelas diretamente; apenas APIs server-side usam service role.
revoke all on table public.product_catalog_overrides from anon, authenticated;
revoke all on table public.product_catalog_history from anon, authenticated;

alter table public.planning_sessions
  add column if not exists admin_effective_snapshot jsonb,
  add column if not exists admin_revision_history jsonb not null default '[]'::jsonb,
  add column if not exists admin_commercial_revision integer not null default 0 check (admin_commercial_revision >= 0),
  add column if not exists admin_commercial_updated_at timestamptz,
  add column if not exists admin_commercial_updated_by text;

create or replace function public.protect_product_catalog_history()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  raise exception 'product_catalog_history_is_append_only';
end;
$$;

drop trigger if exists product_catalog_history_append_only on public.product_catalog_history;
create trigger product_catalog_history_append_only
before update or delete on public.product_catalog_history
for each row execute function public.protect_product_catalog_history();

create or replace function public.protect_admin_commercial_history()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
  old_len integer := jsonb_array_length(coalesce(old.admin_revision_history, '[]'::jsonb));
  new_len integer := jsonb_array_length(coalesce(new.admin_revision_history, '[]'::jsonb));
  i integer;
  admin_changed boolean;
begin
  admin_changed :=
       new.admin_effective_snapshot is distinct from old.admin_effective_snapshot
    or new.admin_revision_history is distinct from old.admin_revision_history
    or new.admin_commercial_revision is distinct from old.admin_commercial_revision
    or new.admin_commercial_updated_at is distinct from old.admin_commercial_updated_at
    or new.admin_commercial_updated_by is distinct from old.admin_commercial_updated_by;

  if not admin_changed then
    return new;
  end if;

  if new.admin_commercial_revision <> old.admin_commercial_revision + 1 then
    raise exception 'admin_commercial_revision_must_increment_once';
  end if;

  if new_len <> old_len + 1 then
    raise exception 'admin_revision_history_must_append_once';
  end if;

  if old_len > 0 then
    for i in 0..old_len - 1 loop
      if (new.admin_revision_history -> i) is distinct from (old.admin_revision_history -> i) then
        raise exception 'admin_revision_history_is_append_only';
      end if;
    end loop;
  end if;

  if new.admin_effective_snapshot is null
     or new.admin_commercial_updated_at is null
     or nullif(btrim(new.admin_commercial_updated_by), '') is null then
    raise exception 'admin_commercial_revision_metadata_required';
  end if;

  return new;
end;
$$;

drop trigger if exists planning_sessions_protect_admin_commercial_history on public.planning_sessions;
create trigger planning_sessions_protect_admin_commercial_history
before update on public.planning_sessions
for each row execute function public.protect_admin_commercial_history();

-- Atomic catalog mutation. Current override and append-only history are committed together.
create or replace function public.rf_admin_write_product_catalog(
  p_product_id text,
  p_product_data jsonb,
  p_active boolean,
  p_actor text,
  p_initial_action text
)
returns table (
  product_id text,
  revision integer,
  action text,
  active boolean,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_current_revision integer;
  v_current_active boolean;
  v_revision integer;
  v_action text;
  v_now timestamptz := now();
begin
  if nullif(btrim(p_product_id), '') is null
     or p_product_data is null
     or nullif(btrim(p_actor), '') is null then
    raise exception 'product_catalog_rpc_invalid_input';
  end if;

  if p_initial_action not in ('CREATE', 'UPDATE', 'DEACTIVATE', 'REACTIVATE') then
    raise exception 'product_catalog_rpc_invalid_action';
  end if;

  select o.revision, o.active
    into v_current_revision, v_current_active
  from public.product_catalog_overrides o
  where o.product_id = p_product_id
  for update;

  if found then
    v_revision := v_current_revision + 1;
    if v_current_active = false and p_active = true then
      v_action := 'REACTIVATE';
    elsif v_current_active = true and p_active = false then
      v_action := 'DEACTIVATE';
    else
      v_action := 'UPDATE';
    end if;
  else
    v_revision := 1;
    v_action := p_initial_action;
  end if;

  insert into public.product_catalog_overrides (
    product_id, product_data, active, revision, updated_at, updated_by
  ) values (
    p_product_id, p_product_data, p_active, v_revision, v_now, p_actor
  )
  on conflict (product_id) do update
    set product_data = excluded.product_data,
        active = excluded.active,
        revision = excluded.revision,
        updated_at = excluded.updated_at,
        updated_by = excluded.updated_by;

  insert into public.product_catalog_history (
    product_id, revision, product_data, active, changed_at, changed_by, action
  ) values (
    p_product_id, v_revision, p_product_data, p_active, v_now, p_actor, v_action
  );

  return query
  select p_product_id, v_revision, v_action, p_active, v_now;
end;
$$;

revoke all on function public.rf_admin_write_product_catalog(text, jsonb, boolean, text, text)
  from public, anon, authenticated;
grant execute on function public.rf_admin_write_product_catalog(text, jsonb, boolean, text, text)
  to service_role;

-- Brigadeiro no tacho: 80 g por convidado real, R$ 12 por porção.
-- Meio a meio = 40 g chocolate + 40 g Ninho na mesma porção de 80 g.
-- A capacidade por hora ainda não foi medida; permanece NULL para não inventar
-- um parâmetro que depois será usado pelo futuro gate de peak capacity.
insert into public.product_catalog_overrides (
  product_id, product_data, active, revision, updated_at, updated_by
) values
(
  'brigadeiro-tacho-chocolate',
  '{"id":"brigadeiro-tacho-chocolate","name":"Brigadeiro no tacho - Chocolate","description":"Porção de 80 g por pessoa","commercialCategory":"Brigadeiro no tacho","operationalGroup":"tacho","productionPerHour":null,"suggestedUnitsPerEquivalentGuest":1,"lotSize":1,"unitPrice":12,"priceUnit":"portion80g","portionGrams":80,"active":true,"consignment":false,"countsAsMainCart":true,"catalogSchemaVersion":1}'::jsonb,
  true, 1, now(), 'migration:20260831'
),
(
  'brigadeiro-tacho-ninho',
  '{"id":"brigadeiro-tacho-ninho","name":"Brigadeiro no tacho - Leite Ninho","description":"Porção de 80 g por pessoa","commercialCategory":"Brigadeiro no tacho","operationalGroup":"tacho","productionPerHour":null,"suggestedUnitsPerEquivalentGuest":1,"lotSize":1,"unitPrice":12,"priceUnit":"portion80g","portionGrams":80,"active":true,"consignment":false,"countsAsMainCart":true,"catalogSchemaVersion":1}'::jsonb,
  true, 1, now(), 'migration:20260831'
),
(
  'brigadeiro-tacho-meio-a-meio',
  '{"id":"brigadeiro-tacho-meio-a-meio","name":"Brigadeiro no tacho - Meio a meio","description":"40 g chocolate + 40 g Leite Ninho por pessoa","commercialCategory":"Brigadeiro no tacho","operationalGroup":"tacho","productionPerHour":null,"suggestedUnitsPerEquivalentGuest":1,"lotSize":1,"unitPrice":12,"priceUnit":"portion80g","portionGrams":80,"active":true,"consignment":false,"countsAsMainCart":true,"catalogSchemaVersion":1}'::jsonb,
  true, 1, now(), 'migration:20260831'
)
on conflict (product_id) do nothing;

insert into public.product_catalog_history (
  product_id, revision, product_data, active, changed_at, changed_by, action
)
select
  product_id,
  revision,
  product_data,
  active,
  updated_at,
  updated_by,
  'CREATE'
from public.product_catalog_overrides
where product_id in (
  'brigadeiro-tacho-chocolate',
  'brigadeiro-tacho-ninho',
  'brigadeiro-tacho-meio-a-meio'
)
on conflict (product_id, revision) do nothing;

comment on table public.product_catalog_overrides is
  'Current server-managed product catalog overrides. Base code catalog remains fallback/seed.';
comment on table public.product_catalog_history is
  'Append-only audit trail for product catalog changes.';
comment on column public.planning_sessions.admin_effective_snapshot is
  'Latest server-authoritative admin commercial revision. Original final_proposal_snapshot remains immutable.';
comment on column public.planning_sessions.admin_revision_history is
  'Append-only metadata/history of administrative commercial revisions.';
comment on function public.rf_admin_write_product_catalog(text, jsonb, boolean, text, text) is
  'Server-only atomic catalog write: current override and append-only history are updated in one transaction.';

commit;
